# Generated by Django 4.2.1 on 2023-06-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyparse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
